name: Test Provider CI
on:
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Verify against testdata
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@6cf9520e68354d86f81c455e8d43eabd58f5c9f5 # v1
      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Configure git
        # Set the default branch to silence the warnings about the default branch name changing
        # The branch doesn't matter here because it's only used for a temp repo for actionlint
        run: git config --global init.defaultBranch master
      - name: Install mise
        uses: jdx/mise-action@c1a019b8d2586943b4dbebc456323b516910e310
        with:
          version: 2026.2.20
      - name: Build & test
        run: cd provider-ci && make all
      - name: Check worktree clean
        uses: pulumi/git-status-check-action@v1
